/* autogenerated wavetables */
#include "wavetable.h"

void init_wavetable() {
	float32_t start = -3.14159265359;
	float32_t step = 2 * 3.14159265359 / WAVETABLE_SIZE;

	for( int i=0; i<WAVETABLE_SIZE; ++i ) {
		wt_sine[i] = arm_sin_f32( start );
		start += step;
	}
}

float32_t wt_sine[WAVETABLE_SIZE] = {};
