---
author: "spielhuus"
categories:
- module
date: 2021-05-30
excerpt: "Summe is a simple DC mixer that allows various applications. The input signals can be simply added. It is also possible to invert the input, which results in a subtraction of the signals. The first input has a default DC voltage. If nothing is connected to this input, a DC offset is applied to the output."
subtitle: "Summe is a simple mixer utility module. It can be used as a mixer, attenuator or attenuverter for AC and DC signals."
tags:
- grundlage
title: summe
version: 1
draft: False
history: 
  - { date: "2021-11-12",
      description: "Bipolar LED and redesign of PCB",
      revision: "2" }
  - { date: "2021-04-01",
      description: "initial commit of project",
      revision: "1" }
references: 
  - { description: "Beginners' Guide to Potentiometers",
      title: "eCircuit",
      url: "http://www.ecircuitcenter.com/Circuits/opdif/opdif.htm" }
  - { description: "Beginners' Guide to Potentiometers",
      title: "ESP",
      url: "https://sound-au.com/pots.htm" }
```{elektron, command="bom", input=["main"], group=TRUE, partlist="../../lib/partlist.yaml"}```
```{elektron, command="erc", input=["main"]}```
```{elektron, command="drc", input=["main"]}```
```{elektron, command="schema", input=["main"], border=TRUE, theme="BlackWhite"}```
```{elektron, command="pcb", input=["main", "panel"], border=TRUE}```
```{elektron, command="gerber", input=["main", "panel"]}```
---

# Construction

The function depends on the patching and settings of the potentiometers. When the potentiometer is at the centre position, the output signal is muted. No output signal is present. When turning to the right, the output will get louder until the output signal is equal to the input. When turning the potentiometer to the left, the output signal will be phase-shifted by 180°.

The first input is wired to a default DC voltage of +5V. With this input is not connected this voltage will be added as an offset to the mixed signal. With the potentiometer, the offset can be adjusted from -5V to +5V.

The output jacks are switched. When something is plugged into an output, this output is removed from the summed output. This channel is a simple attenuverter.

```{latex echo=FALSE, fig.align='center', fig.cap='Figure 1: summe block diagram'}
\documentclass[border=2mm]{standalone}
\usepackage{tikz}
\usepackage{circuitikz}

\begin{document}
\ctikzset{blocks/thickness=2,switches/thickness=1.5}
\begin{circuitikz}[line width=2pt,scale=1.5,font=\sffamily,every node/.style={scale=1.5}]

  \draw (0, 0) node[left] {IN} to (1,0) 
    to[amp] ++(3,0)
    (4.5, 0) node[spdt](Sw4){} 
    (Sw4.out 1) to[short, -o] ++(1,0) node[right] {OUT}
    (Sw4.out 2) to[short, -*] ++(0.5,0);

  \draw (0, 2) node[left] {IN} to (1,2)
    to[amp] ++(3,0)
    (4.5, 2) node[spdt](Sw3){} (4,2) 
    (Sw3.out 1) to ++(1,0) node[right] {OUT}
    (Sw3.out 2) to[short, -*] ++(0.5,0);

  \draw (0, 4) node[left] {IN} to (1,4)
    to[amp] ++(3,0)
    (4.5, 4) node[spdt](Sw2){} (4,4) 
    (Sw2.out 1) to ++(1,0) node[right] {OUT}
    (Sw2.out 2) to[short, -*] ++(0.5,0);

  \draw (0.5, 6) 
    node[spdt,xscale=-1](Swin){} 
    (Swin.out 1) node[left] {IN}
    (Swin.out 2) node[left] {+5V}
    (Swin.in) to (1,6) to[amp] ++(3,0)

    (4.5, 6) node[spdt](Sw1){} (4,6) 
    (Sw1.out 1) to ++(1,0) node[right] {OUT}
    (Sw1.out 2) to ++(0.5,0)
    to ++(0,-6.5);

  \draw (5.6,-1.3) node [adder](sum) {}
    (sum.south) to ++(0,-0.5) 
    to[short,-o] ++(0.4,0) node[right] {OUT};

\end{circuitikz}
\end{document}
```

One interesting thing about the circuit is the attenuverter section. It uses an OPAMP in a differential configuration[[1]](http://www.ecircuitcenter.com/Circuits/opdif/opdif.htm). The resistors $R_3$ and $R_4$ are replaced with a potentiometer to make them adjustable.

```{python echo=FALSE, output="hide", fig.align="center", fig.cap="Figure 2: Attenuverter"}
from elektron import Circuit, Draw, Element, Label, Line, Dot, Simulation

draw = (Draw(["/usr/share/kicad/symbols"])
  + Label("IN").rotate(180) 
  + Line().right().length(10.16)
  + (dot1 := Dot()) 
  + Line().right().length(10.16)
  + (dot2 := Dot())
  + Element("R3", "Device:R", unit=1, value="47k")
  + (dot3 := Dot())
  + Element("R4", "Device:R", unit=1, value="47k")
  + Element("GND", "power:GND", value="GND")

  + Line().at(dot1).down().length(3*1.27)
  + Element("RV1", "Device:R_Potentiometer", value="100k",
                 Spice_Netlist_Enabled="Y",
                 Spice_Primitive="X",
                 Spice_Model="Potentiometer").anchor(1)
  + Element("GND", "power:GND", value="GND").at("RV1", "3")

  + Line().at(dot2).right().length(2.54)
  + Element("R1", "Device:R", unit=1, value="100k").rotate(90)
  + Element("U1", "Amplifier_Operational:TL072", unit=1, value="TL072",
                 Spice_Netlist_Enabled="Y",
                 Spice_Primitive="X",
                 Spice_Model="TL072c").anchor(2).mirror('x')
                 
  + Line().at(dot3).tox("RV1", "2")
  + Line().at(dot3).right().length(10.16)
  + Line().toy("U1", "3")
  + Line().tox("U1", "3")

  + Dot().at("U1", "1")
  + Line().up().length(5*2.54)
  + Element("R2", "Device:R", value="100k").rotate(270).tox("U1", "2")
  + Line().toy("U1", "2")
  + Dot()

  + Line().at("U1", "1").right().length(2.54)
  + Label("OUT")

  + Element("U1", "Amplifier_Operational:TL072", unit=3, value="TL072",
                 Spice_Netlist_Enabled="Y",
                 Spice_Primitive="X",
                 Spice_Model="TL072c", on_schema="no").at((100.0,100.0))
  + Element("+15V", "power:+15V", value="+15V", on_schema="no").at("U1", "8")
  + Element("-15V", "power:-15V", value="-15V", on_schema="no").rotate(180).at("U1", "4")
  + Element("U1", "Amplifier_Operational:TL072", unit=2, value="TL072",
                 Spice_Netlist_Enabled="Y",
                 Spice_Primitive="X",
                 Spice_Model="TL072c", on_schema="no").at((120.0,100.0))
)

circuit = draw.circuit(["../../lib/spice"])
circuit.voltage("1", "+15V", "GND", "DC 15V")
circuit.voltage("2", "-15V", "GND", "DC -15V")
circuit.voltage("3", "IN", "GND", "DC 5V AC 5V SIN(0, 5V, 1k)")
circuit.control('''let rb_act = 0
let r_step = 0.01
let r_stop = 1
while rb_act le r_stop
  alterparam potentiometer set = $&rb_act
  mc_source
  op
  let rb_act = rb_act + r_step
end
''')

simulation = Simulation(circuit)
attenuverter = simulation.run()

import numpy as np
sweep = []
lin = []
perc = []
for i in range(1,100):
  sweep.append(attenuverter[f'op{i}']['out'][0])
  lin.append(-5 + i * 0.1)
  perc.append(i)
adata = {}
adata['OUT'] = sweep
adata['linear'] = lin
adata['percentage'] = perc

draw.plot(scale=6, theme='BlackWhite')
```

$$
\begin{array}{c}
Vout = \Bigl(1 + \frac{R2}{R1}\Bigr) \Bigl(\frac{R4}{R3+R4}\Bigr) * V2 - \Bigl(\frac{R2}{R1}\Bigr) * V1
\end{array}
$$

Above is the formula of the OPAMP differential amplifier. There are also the Resistors $R_5$ and $R_6$. These resistors make the response of the potentiometer logarithmic [[2]](https://sound-au.com/pots.htm). To calculate that these Resistors are in parallel to the Resistors $R_3$ and $R_4$.

$$
\begin{array}{c}
Vout = \Bigl(1 + \frac{R2}{R1}\Bigr) \Bigl(\frac{\Bigl(\frac{R4*R6}{R3+R5}\Bigr)}{\Bigl(\frac{R3 * R5}{R3+R5}\Bigr)+\Bigl(\frac{R4 * R6}{R3+R5}\Bigr)}\Bigr) * V2 - \Bigl(\frac{R2}{R1}\Bigr) * V1
\end{array}
$$

```{d3, element="attenuverter", x="percentage", y="OUT,linear", data="py$adata", width="600", height="400", fig.align='center', fig.cap="Figure 3: Attenuverter sweep", yLabel="Amplitude [V]", xLabel="Potentiometer [%]"}```

The calculation shows the Result with a 5V input and a potentiometer sweep from 0-100%. The last curve shows the logarithmic result simulated with spice. It overlaps the calculated line.

It may be that the summing amplifier is not stable and self oscillates. In this case, small capacitors can be added to stabilize the signal.

{{< bom >}}

{{< callout summe main panel >}}

{{< report summe main >}}

{{< image "/summe-failure.jpg" "Figure 4: Opamp Failure" >}}

# Usage

The first input jack is wired to 5 volts when nothing is connected.

All channels are mixed to the out jack. when something is connected to the channel out, this channel is removed from the overall mix.

_mixer_
* connect the different channels from audio or cv sources to the in jacks.
* connect the out jack to something
* turn the pots clockwise to adjust the volume.

_attenuverter_
* connect all or a single channel. 
* when the pot knob is turned counterclockwise, the signal is inverted.






