# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

group :jekyll_plugins do
    gem "jekyll-feed", "~> 0.6"
    gem "jekyll-sitemap"
    gem "jekyll-paginate-v2"
    gem "jekyll-seo-tag"
    gem 'jekyll-toc'
    gem 'jekyll-assets'
end