# frozen_string_literal: true

source "https://rubygems.org"

#git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "jekyll", "~> 4.2.0"

group :jekyll_plugins do
    gem "jekyll-feed"
    gem "jekyll-sitemap"
    gem "jekyll-paginate-v2"
    gem "jekyll-seo-tag"
    gem 'jekyll-toc'
    gem 'jekyll-assets'
end