import os

from SCons.Node import NodeList

Import(['env', 'PCB', 'GERBER', 'SCHEMA', 'REPORTS', 'FILES', 'HTML'])
DRC = NodeList()

project = 'tiefpass'
for board in ['main', 'mount', 'panel'] :
    #REPORTS += env.preflight(f'{board}/{project}_{board}_report.json', f'{board}/{board}.pro', project_name=project)
    SCHEMA += env.schema(f'{board}/{project}_{board}_schematic.svg', f'{board}/{board}.kicad_sch')
    PCB += env.pcb(f'{board}/{project}_{board}_pcb.pdf', f'{board}/{board}.kicad_pcb')
    GERBER += env.gerbers(f'{board}/{project}_{board}_JLCPCB.zip', f'{board}/{board}.kicad_pcb')
    DRC += env.drc(f'{board}/{project}_{board}_drc.json', f'{board}/{board}.kicad_pcb', project_name=project)
    REPORTS += env.bom(f'{board}/{project}_{board}_bom.json', f'{board}/{board}.kicad_sch', project_name=project)

    #Clean(os.path.join(board, f'{board}.pro'), os.path.join(board, 'fp-info-cache'))
    #Clean(os.path.join(board, f'{board}.pro'), os.path.join(board, f'{board}-cache.lib'))
    #Clean(os.path.join(board, f'{board}.pro'), Glob(f'{board}/*-bak'))

HTML += env.nbconvert(f'{project}.html', f'{project}.ipynb')

FILES += Glob('*.jpg')
