---
date: "2022-01-01T13:09:13-06:00"
author: "spielhuus"
excerpt: "The CD4069UB device consists of six CMOS inverter circuits. These devices are intended for all general-purpose inverter applications. It is not ideal for linear amplification, but can be used as such and will add a lot of soft-clipping. This makes this device special for musical usage and can be found in guitar distortion pedals <a href='http://www.runoffgroove.com/ubescreamer.html'>[3]</a> or the wasp filter <a href='https://www.schmitzbits.de/wasp.html'>[4]</a>."
subtitle: "Linear amplification with the CD4069UBE."
tags:
- grundlage
categories:
- article
title: "CMOS: 4069"
has_hero: false

references: 
  - { description: "Datasheet",
      title: "CD4069UB",
      url: "https://www.ti.com/lit/ds/schs054e/schs054e.pdf" }
  - { description: "CMOS Linear Applications",
      title: "AN-0088",
      url: "http://www.sdiy.org/philgallo/hfvco/AN-0088.pdf" }
  - { description: "ESP",
      title: "State Variable Filters",
      url: "https://sound-au.com/articles/state-variable.htm" } 
  - { description: "TS-808 workalike built around the CD4049UBE logic IC",
      title: "UBE Screamer",
      url: "http://www.runoffgroove.com/ubescreamer.html" }
  - { description: "Jürgen Haibles clone of the EDP Wasp VCF from René Schmitz.",
      title: "WASP Filter",
      url: "https://www.schmitzbits.de/wasp.html" }
  - { description: "One more simple VCF",
      title: "electromusic-forum",
      url: "https://electro-music.com/forum/viewtopic.php?t=69887" } 
  - { description: "CMOS MS20 Filter",
      title: "MS20",
      url: "http://www.sdiy.org/destrukto/files/cmosed_ms20_filter_11-18-2005.pdf" } 
version: 0
---

```{latex echo=FALSE, fig.align='right', fig.cap='Figure 1: CD4069 pinout'}
\documentclass[border=2mm]{standalone}
\usepackage{tikz}
\usepackage{circuitikz}

\begin{document}
\begin{circuitikz}[thick,scale=2.5, every node/.style={scale=2.5}]
    \ctikzset{multipoles/thickness=3}
    \ctikzset{multipoles/external pins thickness=2}
    \ctikzset{logic ports=ieee,
              logic ports/scale=0.35}

    \draw (0,0) node[dipchip,
        num pins=14,
        hide numbers,
        external pins width=0.3,
        external pad fraction=4](C){};
    \draw[line width=0.2] (C.bpin 1) -- ++(0.5,0) to[inline not, -] ++(0.0,-0.56) -- (C.bpin 2);
    \draw[line width=0.2] (C.bpin 3) -- ++(0.5,0) to[inline not, -] ++(0.0,-0.56) -- (C.bpin 4);
    \draw[line width=0.2] (C.bpin 5) -- ++(0.5,0) to[inline not, -] ++(0.0,-0.56) -- (C.bpin 6);
    \draw[line width=0.2] (C.bpin 8) -- ++(-0.5,0) to[inline not, -] ++(0.0,0.56) -- (C.bpin 9);
    \draw[line width=0.2] (C.bpin 10) -- ++(-0.5,0) to[inline not, -] ++(0.0,0.56) -- (C.bpin 11);
    \draw[line width=0.2] (C.bpin 12) -- ++(-0.5,0) to[inline not, -] ++(0.0,0.56) -- (C.bpin 13);
    \foreach \n in {1,...,7}
        \node [left, font=\tiny] at (C.bpin \n) {\texttt{\n}};
    \foreach \n in {8,...,14}
        \node [right, font=\tiny] at (C.bpin \n) {\texttt{\n}};
    \node [right, font=\tiny] at (C.bpin 7) {\texttt{GND}};
    \node [left, font=\tiny] at (C.bpin 14) {\texttt{VCC}};
\end{circuitikz}
\end{document}
```
The basic usage and pin mapping is explained in the datasheet [[1]](https://www.ti.com/lit/ds/schs054e/schs054e.pdf). It is not very common to use this chip for linear amplification, especially in our days where opamps are very cheap to get. But there is also an application note [[2]](http://www.sdiy.org/philgallo/hfvco/AN-0088.pdf) that explains the basic usage. It will not go into too many details, we will have to figure out some details on our own.

For linear amplification only the unbuffered (UBE) chip can be used, the buffered chip will produce a binary output. Also, the chip should be powered by +5V/GND. With higher voltage, the heat dissipation will be too big and the chip will be damaged. the chip is powered on pins 7 and 14 with +5V and Ground. the other pins can be used as an amplifier.

# Buffer

The simplest circuit, to begin with, is a voltage follower or buffer. The buffer configuration looks similar to the opamp buffer. But there are some differences. The first important difference is that the feedback will also do the biasing of the input signal. when an ac signal is applied to the buffer the output will be a DC signal, as long as the chip is able to provide the needed biasing feedback. The gain can be calculated similarly to the opamp configuration. But there will be less gain as we would expect from the calculation.


```{python echo=FALSE, results="hide", fig.align="center", fig.cap="Figure 4: Linear amplifier"}
from elektron import Circuit, Draw, Element, Label, Line, Dot, Simulation

draw = (Draw(["/usr/share/kicad/symbols"])
  + Label("IN").rotate(180)
  + Element("C1", "Device:C", value="47n", Spice_Netlist_Enabled="Y").rotate(90)
  + Element("R1", "Device:R", value="100k", Spice_Netlist_Enabled="Y").rotate(90)
  + (u1_dot_in := Dot())
  + Element("U1", "4xxx:4069", value="U1", unit=1,
            Spice_Netlist_Enabled='Y',
            Spice_Primitive='X',
            Spice_Model='4069UB',
            Spice_Node_Sequence="1 2 14 7").anchor(1)
  + (u1_dot_out := Dot())
  + Line().right().length(2.54)
  + Label("OUT")

  + Line().at(u1_dot_out).up().length(5*2.54)
  + Element("R2", "Device:R", value="100k", Spice_Netlist_Enabled="Y").rotate(270).tox(u1_dot_in)
  + Line().down().toy(u1_dot_in)

  + Element("U1", "4xxx:4069", value="CD4069", unit=7, on_schema=False).at((50.8, 50.8))
  + Element("+5V", "power:+5V", value="+5V", on_schema=False).at("U1", "14")
  + Element("GND", "power:GND", value="GND", on_schema=False).at("U1", "7"))

circuit = draw.circuit(["lib/spice"])
circuit.voltage("1", "+5V", "GND", "DC 5V")
circuit.voltage("2", "IN", "GND", "DC 5 AC 2.5V SIN(0 2.5V 100)")
circuit.control('''let r_act = 100k
let r_step = 10k
let r_stop = 500k
while r_act le r_stop
  alter R2 r_act
  tran 40us 10ms
  let r_act = r_act + r_step
end
''')
simulation = Simulation(circuit)
buffer = simulation.run()

draw.plot(scale=6, theme='BlackWhite')
```

This is the first setup with the 4069 as a voltage follower. C1 and C2 are DC blocking capacitors. When we choose R1 and R2 as 100kOhm we would expect a gain of one.

```{d3 element="buffer", x="time", y="in", yRange="out", data="buffer.tran", width="600", height="400", fig.align="center", fig.cap="Figure 5: linear amplifier simulation", yLabel="Amplitude [V]", xLabel="Time [ms]", range="R2"}```

The blue line is the input signal (5V p2p) and the red is the output signal with 100kOhm resistors. The output is a little less than expected. For the other signals, the resistor R2 is replaced with 125kΩ, 150kΩ, 175kΩ and 200kΩ. With 150kΩ the gain is roughly one. We also see that the output is not symmetrical. The clipping occurs earlier for the negative part of the signal. With the higher gain, the signal is soft clipped.

# adder

The cmos inverter can also be used as a summing amplifier. In this example, two sinusoidal signals are added. The setup is the same as an Opamp summing amplifier. The gain can be adjusted with the feedback resistor.

```{python echo=FALSE, results="hide", fig.align="center", fig.cap="Figure 4: Linear amplifier"}
from elektron import Circuit, Draw, Element, Label, Line, Dot, Simulation

draw = (Draw(["/usr/share/kicad/symbols"])
  + Label("IN2").rotate(180)
  + Element("C2", "Device:C", value="47n", Spice_Netlist_Enabled="Y").rotate(90)
  + Element("R2", "Device:R", value="100k", Spice_Netlist_Enabled="Y").rotate(90)
  + Line().right().length(2.54)
  + (adder := Dot())
  + Line().up().length(4*2.54)
  + Line().left().length(2.54)
  + Element("R1", "Device:R", value="100k", Spice_Netlist_Enabled="Y").rotate(270)
  + Element("C1", "Device:C", value="47n", Spice_Netlist_Enabled="Y").rotate(270)
  + Label("IN1").rotate(180)

  # + Element("C1", "Device:C", value="47n", Spice_Netlist_Enabled="Y").rotate(90).at(adder)
  + Line().right().length(2.54).at(adder)
  + (u1_dot_in := Dot())
  + Element("U1", "4xxx:4069", value="U1", unit=1,
            Spice_Netlist_Enabled='Y',
            Spice_Primitive='X',
            Spice_Model='4069UB',
            Spice_Node_Sequence="1 2 14 7").anchor(1)
  + (u1_dot_out := Dot())
  + Label("OUT")

  + Line().at(u1_dot_out).up().length(5*2.54)
  + Element("R3", "Device:R", value="47k", Spice_Netlist_Enabled="Y").rotate(270).tox(u1_dot_in)
  + Line().down().toy(u1_dot_in)

  + Element("U1", "4xxx:4069", value="CD4069", unit=7, on_schema=False).at((50.8, 50.8))
  + Element("+5V", "power:+5V", value="+5V", on_schema=False).at("U1", "14")
  + Element("GND", "power:GND", value="GND", on_schema=False).at("U1", "7"))

circuit = draw.circuit(["lib/spice"])
circuit.voltage("1", "+5V", "GND", "DC 5V")
circuit.voltage("2", "IN1", "GND", "DC 5 AC 2.5V SIN(0 2.5V 500)")
circuit.voltage("3", "IN2", "GND", "DC 5 AC 2.5V SIN(0 2.5V 1k)")
circuit.control('''
tran 40us 10ms
''')
simulation = Simulation(circuit)
adder = simulation.run()

draw.plot(scale=6, theme='BlackWhite')
```

This is the first setup with the 4069 as a voltage follower. C1 and C2 are DC blocking capacitors. When we choose R1 and R2 as 100kOhm we would expect a gain of one.

```{d3 element="adder", x="time", y="out", data="adder.tran", width="600", height="400", fig.align="center", fig.cap="Figure 5: linear amplifier simulation", yLabel="Amplitude [V]", xLabel="Time [ms]"}```

# Integrator

```{python echo=FALSE, results="hide", fig.align="center", fig.cap="Figure 4: Linear amplifier"}
from elektron import Circuit, Draw, Element, Label, Line, Dot, Simulation
import numpy as np

draw = (Draw(["/usr/share/kicad/symbols"])
  + Label("IN").rotate(180)
  + Element("R1", "Device:R", value="3k", Spice_Netlist_Enabled="Y").rotate(90)
  + (u1_dot_in := Dot())
  + Element("U1", "4xxx:4069", value="U1", unit=1,
            Spice_Netlist_Enabled='Y',
            Spice_Primitive='X',
            Spice_Model='4069UB',
            Spice_Node_Sequence="1 2 14 7").anchor(1)
  + (u1_dot_out := Dot())
  + Line().length(2.54)
  + Label("OUT")

  + Line().at(u1_dot_out).up().length(5*2.54)
  + (fb_dot1 := Dot())
  + Element("C2", "Device:C", value="10n", Spice_Netlist_Enabled="Y").rotate(270).tox(u1_dot_in)
  + (fb_dot2 := Dot())
  + Line().down().toy(u1_dot_in)

  + Line().at(fb_dot1).up().length(4*2.54)
  + Element("R2", "Device:R", value="3k", Spice_Netlist_Enabled="Y").rotate(270).tox(fb_dot2)
  + Line().down().toy(fb_dot2)

  + Element("U1", "4xxx:4069", value="CD4069", unit=7, on_schema=False).at((50.8, 50.8))
  + Element("+5V", "power:+5V", value="+5V", on_schema=False).at("U1", "14")
  + Element("GND", "power:GND", value="GND", on_schema=False).at("U1", "7"))

circuit = draw.circuit(["lib/spice"])
circuit.voltage("1", "+5V", "GND", "DC 5V")
circuit.voltage("2", "IN", "GND", "AC 5V SIN(0 5V 500)")
circuit.control('''
ac dec 30 10 1k
''')
simulation = Simulation(circuit)
filter = simulation.run()

for key, value in filter.items():
  if key.startswith("ac"):
    for k, v in value.items():
      if k == "frequency":
        filter[key][k] = v[1:]
      else:
        filter[key][k] = 20*np.log10(np.absolute(v))[1:]

draw.plot(scale=6, theme='BlackWhite')
```

This is the first setup with the 4069 as a voltage follower. C1 and C2 are DC blocking capacitors. When we choose R1 and R2 as 100kOhm we would expect a gain of one.

```{d3 element="filter", x="frequency", y="out", data="filter.ac1", width="600", height="400", fig.align="center", fig.cap="Figure 5: linear amplifier simulation", yLabel="Amplitude [V]", xLabel="Time [ms]"}```

# Low pass filter

The simplest circuit, to begin with, is a voltage follower or buffer. The buffer configuration looks similar to the opamp buffer. But there are some differences. The first important difference is that the feedback will also do the biasing of the input signal. when an ac signal is applied to the buffer the output will be a DC signal, as long as the chip is able to provide the needed biasing feedback. The gain can be calculated similarly to the opamp configuration. But there will be less gain as we would expect from the calculation.

```{python echo=FALSE, results="hide", fig.align="center", fig.cap="Figure 6: State variable filter"}
from elektron import Circuit, Draw, Element, Label, Line, Dot, Simulation
import numpy as np

draw = (Draw(["/usr/share/kicad/symbols"])
  + Label("IN").rotate(180)
  + Element("C1", "Device:C", value="1u", Spice_Netlist_Enabled="Y").rotate(90)
  + (u1_dot_in := Dot())
  + Element("R1", "Device:R", value="10k", Spice_Netlist_Enabled="Y").rotate(90)
  + Element("U1", "4xxx:4069", value="4069", unit=1, Spice_Primitive="X", Spice_Model="4069UB", Spice_Node_Sequence="1 2 14 7")
  + (u1_dot_out := Dot())

  # + Element("R3", "Device:R", value="100k", Spice_Netlist_Enabled="Y").rotate(90)
  + (u2_dot_in := Dot())
  + Element("U2", "4xxx:4069", value="4069", unit=1, Spice_Primitive="X", Spice_Model="4069UB", Spice_Node_Sequence="1 2 14 7")
  + (u2_dot_out := Dot())

  + Element("R5", "Device:R", value="10k", Spice_Netlist_Enabled="Y").rotate(90)
  + (u3_dot_in := Dot())
  + Element("U3", "4xxx:4069", value="4069", unit=1, Spice_Primitive="X", Spice_Model="4069UB", Spice_Node_Sequence="1 2 14 7")
  + (u3_dot_out := Dot())

  + Element ("R6", "Device:R", value="10k", Spice_Netlist_Enabled="Y").rotate(90)
  + (u4_dot_in := Dot())
  + Element("U4", "4xxx:4069", value="4069", unit=1, Spice_Primitive="X", Spice_Model="4069UB", Spice_Node_Sequence="1 2 14 7")
  + (u4_dot_out := Dot())

  # + Line().up().length(12.7).at(u1_dot_out)
  # + Element("R2", "Device:R", value="100k", Spice_Netlist_Enabled="Y").rotate(270).tox(u1_dot_in)
  # + (r2_out := Dot())
  # + Line().down().toy(u1_dot_in)

  + Line().up().length(12.7).at(u2_dot_out)
  + Label("HP")
  + Element("R4", "Device:R", value="10k", Spice_Netlist_Enabled="Y").rotate(270).tox(u2_dot_in)
  + (r4_out := Dot())
  + Line().down().toy(u2_dot_in)

  + Line().up().length(12.7).at(u3_dot_out)
  + Label("BP")
  + (bp := Dot())
  + Element("C3", "Device:C", value="0.1u", Spice_Netlist_Enabled="Y").rotate(270).tox(u3_dot_in)
  + Line().down().toy(u3_dot_in)

  + Line().up().length(12.7).at(u4_dot_out)
  + Label("LP")
  + (lp := Dot())
  + Element("C4", "Device:C", value="0.1u", Spice_Netlist_Enabled="Y").rotate(270).tox(u4_dot_in)
  + Line().down().toy(u4_dot_in)

  + Line().up().length(10.16).at(lp)
  + Element("R7", "Device:R", value="100k", Spice_Netlist_Enabled="Y").rotate(270).tox(r4_out)
  + Line().down().toy(r4_out)

  + Line().up().length(20.32).at(bp)
  + Element("R8", "Device:R", value="10k", Spice_Netlist_Enabled="Y").rotate(270).tox(u1_dot_in)
  + Line().down().toy(u1_dot_in)

  + Element("U1", "4xxx:4069", value="4069", unit=7, Spice_Model="4069UB", Spice_Node_Sequence="1 2 14 7", on_schema="no").at((50.8, 50.8))
  + Element("GND", "power:GND", value="GND", unit=1, on_schema="no").at("U1", "7")
  + Element("+5V", "power:+5V", value="+5V", unit=1, on_schema="no").at("U1", "14")

  + Element("U2", "4xxx:4069", value="4069", unit=7, Spice_Model="4069UB", Spice_Node_Sequence="1 2 14 7", on_schema="no").at((71.12, 50.8))
  + Element("GND", "power:GND", value="GND", unit=1, on_schema="no").at("U2", "7")
  + Element("+5V", "power:+5V", value="+5V", unit=1, on_schema="no").at("U2", "14")

  + Element("U3", "4xxx:4069", value="4069", unit=7, Spice_Model="4069UB", Spice_Node_Sequence="1 2 14 7", on_schema="no").at((91.44, 50.8))
  + Element("GND", "power:GND", value="GND", unit=1, on_schema="no").at("U3", "7")
  + Element("+5V", "power:+5V", value="+5V", unit=1, on_schema="no").at("U3", "14")

  + Element("U4", "4xxx:4069", value="4069", unit=7, Spice_Model="4069UB", Spice_Node_Sequence="1 2 14 7", on_schema="no").at((111.76, 50.8))
  + Element("GND", "power:GND", value="GND", unit=1, on_schema="no").at("U4", "7")
  + Element("+5V", "power:+5V", value="+5V", unit=1, on_schema="no").at("U4", "14"))

circuit = draw.circuit(["lib/spice"])
circuit.voltage("1", "+5V", "GND", "DC 15V")
circuit.voltage("2", "IN", "GND", "AC 5V SIN(0 2V 1k)")
circuit.control('''
let r_act = 10k
let r_step = 5k
let r_stop = 100k
while r_act le r_stop
  alter R5 r_act
  alter R6 r_act
  ac dec 30 10 1k
  let r_act = r_act + r_step
end
''')
# circuit.control('''
# ac dec 10 200 7K
# ''')

simulation = Simulation(circuit)
# svf_data = simulation.tran("1us", "10ms", "0ms")
# print(len(svf_data))
lp = simulation.run()

for key, value in lp.items():
  if key.startswith("ac"):
    for k, v in value.items():
      if k == "frequency":
        lp[key][k] = v[1:]
      else:
        lp[key][k] = 20*np.log10(np.absolute(v))[1:]

draw.plot(scale=6, theme='BlackWhite')
```

This is the first setup with the 4069 as a voltage follower. C1 and C2 are DC blocking capacitors. When we choose R1 and R2 as 100kOhm we would expect a gain of one.

```{d3 element="lp_ac", x="frequency", yRange="lp", data="lp.ac", width="600", height="400", fig.align="center", xType="scaleLog", fig.cap="Figure 7: State variable filter simulation" yLabel="Amplitude [V]", xLabel="Frequency [Hz]"}```

# State Variable Filter 

A state variable filter is constructed with two integrator amplifier and a summer. The integrators are low bass filters. The output of both is mixed back to the input. This will give three resonses. A High pass, band pass and low pass response.

```{python echo=FALSE, results="hide", fig.align="center", fig.cap="Figure 6: State variable filter"}
from elektron import Circuit, Draw, Element, Label, Line, Dot, Simulation
import numpy as np

draw = (Draw(["/usr/share/kicad/symbols"])
  + Label("IN").rotate(180)
  + Element("C1", "Device:C", value="1u", Spice_Netlist_Enabled="Y").rotate(90)
  + (input := Dot())
  + Element("R1", "Device:R", value="100k", Spice_Netlist_Enabled="Y").rotate(90)
  + (u1_dot_in := Dot())
  + Element("U1", "4xxx:4069", value="4069", unit=1, Spice_Primitive="X", Spice_Model="4069UB", Spice_Node_Sequence="1 2 14 7")
  + (u1_dot_out := Dot())

  + Element("R3", "Device:R", value="100k", Spice_Netlist_Enabled="Y").rotate(90)
  + (u2_dot_in := Dot())
  + Element("U2", "4xxx:4069", value="4069", unit=1, Spice_Primitive="X", Spice_Model="4069UB", Spice_Node_Sequence="1 2 14 7")
  + (u2_dot_out := Dot())

  + Element("R5", "Device:R", value="10k", Spice_Netlist_Enabled="Y").rotate(90)
  + (u3_dot_in := Dot())
  + Element("U3", "4xxx:4069", value="4069", unit=1, Spice_Primitive="X", Spice_Model="4069UB", Spice_Node_Sequence="1 2 14 7")
  + (u3_dot_out := Dot())

  + Element ("R6", "Device:R", value="10k", Spice_Netlist_Enabled="Y").rotate(90)
  + (u4_dot_in := Dot())
  + Element("U4", "4xxx:4069", value="4069", unit=1, Spice_Primitive="X", Spice_Model="4069UB", Spice_Node_Sequence="1 2 14 7")
  + (u4_dot_out := Dot())

  + Line().up().length(12.7).at(u1_dot_out)
  + Element("R2", "Device:R", value="100k", Spice_Netlist_Enabled="Y").rotate(270).tox(u1_dot_in)
  + (r2_out := Dot())
  + Line().down().toy(u1_dot_in)

  + Line().up().length(12.7).at(u2_dot_out)
  + Label("HP")
  + Element("R4", "Device:R", value="100k", Spice_Netlist_Enabled="Y").rotate(270).tox(u2_dot_in)
  + (r4_out := Dot())
  + Line().down().toy(u2_dot_in)

  + Line().up().length(12.7).at(u3_dot_out)
  + Label("BP")
  + (bp := Dot())
  + Element("C3", "Device:C", value="10n", Spice_Netlist_Enabled="Y").rotate(270).tox(u3_dot_in)
  + Line().down().toy(u3_dot_in)

  + Line().up().length(12.7).at(u4_dot_out)
  + Label("LP")
  + (lp := Dot())
  + Element("C4", "Device:C", value="10n", Spice_Netlist_Enabled="Y").rotate(270).tox(u4_dot_in)
  + Line().down().toy(u4_dot_in)

  + Line().up().length(10.16).at(lp)
  + Element("R7", "Device:R", value="100k", Spice_Netlist_Enabled="Y").rotate(270).tox(r4_out)
  + Line().down().toy(r4_out)

  + Line().up().length(20.32).at(bp)
  + Element("R8", "Device:R", value="100k", Spice_Netlist_Enabled="Y").rotate(270) #.tox(input) #r2_out)
  + Element("C10", "Device:C", value="1u", Spice_Netlist_Enabled="Y").rotate(270).tox(r2_out)
  + Line().down().toy(input) #r2_out)

  + Element("U1", "4xxx:4069", value="4069", unit=7, Spice_Model="4069UB", Spice_Node_Sequence="1 2 14 7", on_schema="no").at((50.8, 50.8))
  + Element("GND", "power:GND", value="GND", unit=1, on_schema="no").at("U1", "7")
  + Element("+5V", "power:+5V", value="+5V", unit=1, on_schema="no").at("U1", "14")

  + Element("U2", "4xxx:4069", value="4069", unit=7, Spice_Model="4069UB", Spice_Node_Sequence="1 2 14 7", on_schema="no").at((71.12, 50.8))
  + Element("GND", "power:GND", value="GND", unit=1, on_schema="no").at("U2", "7")
  + Element("+5V", "power:+5V", value="+5V", unit=1, on_schema="no").at("U2", "14")

  + Element("U3", "4xxx:4069", value="4069", unit=7, Spice_Model="4069UB", Spice_Node_Sequence="1 2 14 7", on_schema="no").at((91.44, 50.8))
  + Element("GND", "power:GND", value="GND", unit=1, on_schema="no").at("U3", "7")
  + Element("+5V", "power:+5V", value="+5V", unit=1, on_schema="no").at("U3", "14")

  + Element("U4", "4xxx:4069", value="4069", unit=7, Spice_Model="4069UB", Spice_Node_Sequence="1 2 14 7", on_schema="no").at((111.76, 50.8))
  + Element("GND", "power:GND", value="GND", unit=1, on_schema="no").at("U4", "7")
  + Element("+5V", "power:+5V", value="+5V", unit=1, on_schema="no").at("U4", "14"))

circuit = draw.circuit(["lib/spice"])
circuit.voltage("1", "+5V", "GND", "DC 15V")
circuit.voltage("2", "IN", "GND", "AC 5V SIN(0 5V 1k)")
circuit.control('''
alter R5 40k
alter R6 40k

let r_act = 10k
let r_step = 1k
let r_stop = 200k
while r_act le r_stop
  alter R3 r_act
  ac dec 30 100 2K
  let r_act = r_act + r_step
end
''')

#alter R5 40k
#alter R6 40k
#ac dec 30 100 2K

simulation = Simulation(circuit)
svf_data = simulation.tran("1us", "10ms", "0ms")
svf = simulation.run()

for key, value in svf.items():
  if key.startswith("ac"):
    for k, v in value.items():
      if k == "frequency":
        svf[key][k] = v[1:]
      else:
        svf[key][k] = np.log10(np.absolute(v))[1:]

draw.plot(scale=6, theme='BlackWhite')
```

This is the first setup with the 4069 as a voltage follower. C1 and C2 are DC blocking capacitors. When we choose R1 and R2 as 100kOhm we would expect a gain of one.

```{d3 element="svf_ac", x="frequency", yRange="bp,hp,lp", data="svf.ac", width="600", height="400", fig.align="center", xType="scaleLog", fig.cap="Figure 7: State variable filter simulation" yLabel="Amplitude [V]", xLabel="Frequency [Hz]"}```

The band pass output is not correct.


```{d3 element="svf_tran", x="time", y="bp,lp,hp", data="svf_data", width="600", height="400", fig.align="center", fig.cap="Figure 7: State variable filter simulation" yLabel="Amplitude [V]", xLabel="Frequency [Hz]"}```

